base_url = "https://gacela-project.com"

title = "Gacela Project"
description = "Gacela Project"
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
    { theme = "demain", filename = "syntax-theme-light.css" },
]

[extra]
author = "Chemaclass"
gtag = "G-TN20QBCH33"

# MENU
[[extra.menu]]
url = "$BASE_URL/docs"
name = "Documentation"

[[extra.menu]]
url = "$BASE_URL/used-in"
name = "Used In"

[[extra.menu]]
url = "https://github.com/gacela-project/gacela"
name = "GitHub"
