base_url = "https://gacela-project.com"

title = "Gacela Project"
description = "Gacela Project"
compile_sass = true
generate_feed = false
theme = "even"

[markdown]
highlight_code = true
highlight_theme = "demain"

[extra]
author = "Chemaclass"
even_title = "Gacela"
even_menu = [
    {url = "$BASE_URL/facade", name = "Facade"},
    {url = "$BASE_URL/factory", name = "Factory"},
    {url = "$BASE_URL/dependency-provider", name = "Dependency Provider"},
    {url = "$BASE_URL/config", name = "Config"},
]
